# Generated by Django 3.2.19 on 2023-08-12 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0003_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivered_on',
            field=models.DateField(blank=True, null=True, verbose_name='Delievered to Client'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='landed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Received TZ'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='owner_mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='received_on',
            field=models.DateField(blank=True, null=True, verbose_name='Received China WH'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='eta',
            field=models.DateField(verbose_name='Estimated Arrival'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
