# Generated by Django 3.2.19 on 2023-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20230812_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='shipments.shipment'),
        ),
    ]
