# Generated by Django 3.2.19 on 2023-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_parcel_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='China WH', editable=False, max_length=20),
        ),
    ]
