# Generated by Django 3.2.19 on 2023-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20230812_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Arrival'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Packed', editable=False, max_length=20),
        ),
    ]
