# Generated by Django 3.2.19 on 2023-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20230812_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='landed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received TZ'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='received_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received China WH'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='shipped_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
