# Generated by Django 3.2.19 on 2023-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20230812_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='received_on',
            field=models.DateField(blank=True, null=True, verbose_name='Received China WH'),
        ),
    ]
